# Generated by Django 4.1.2 on 2022-10-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('codigo', models.SlugField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(blank=True, default=True)),
                ('unidades', models.CharField(choices=[('u', 'Unidades')], default='u', max_length=2)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.seccion')),
            ],
        ),
    ]
