# Generated by Django 4.1.2 on 2022-10-06 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instrumentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('codigo', models.SlugField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(blank=True, default=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades_peso', models.CharField(choices=[('lb', 'libras'), ('kg', 'Kilogramos')], default='kg', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('nopagado', 'No Pagado'), ('pagado', 'Pagado')], default='nopagado', max_length=10)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario_orden_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='TextosInstrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('autor', models.CharField(max_length=100, unique=True)),
                ('editorial', models.CharField(max_length=100, unique=True)),
                ('edicion', models.CharField(max_length=100, unique=True)),
                ('codigo', models.SlugField()),
                ('disponible', models.BooleanField(blank=True, default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.seccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='ordenproducto',
            name='texto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.textosinstrumento'),
        ),
    ]
