# Generated by Django 4.1.2 on 2022-10-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_instrument_orden_ordenproducto_textosinstrumento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textosinstrumento',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textosinstrumento',
            name='edicion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='textosinstrumento',
            name='editorial',
            field=models.CharField(max_length=100),
        ),
    ]
