# Generated by Django 4.1.2 on 2022-10-07 05:16

from django.db import migrations, models
import instrumentos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0003_alter_textosinstrumento_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='codigo',
            field=models.SlugField(validators=[instrumentos.validators.validar_numero_caracteres_7]),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[instrumentos.validators.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(unique='False'),
        ),
        migrations.AlterField(
            model_name='ordenproducto',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[instrumentos.validators.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='ordenproducto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[instrumentos.validators.validar_positivo]),
        ),
        migrations.AlterField(
            model_name='textosinstrumento',
            name='codigo',
            field=models.SlugField(validators=[instrumentos.validators.validar_numero_caracteres_8, instrumentos.validators.validar_codigo_texto]),
        ),
        migrations.AlterField(
            model_name='textosinstrumento',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[instrumentos.validators.validar_positivo]),
        ),
    ]
