# Generated by Django 4.1.2 on 2022-10-07 05:45

from django.db import migrations, models
import instrumentos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0004_alter_instrument_codigo_alter_instrument_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateField(unique='False', validators=[instrumentos.validators.validar_fecha]),
        ),
    ]
